from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from enum import StrEnum

from subsched.agents.process import redact_sensitive_command_audit
from subsched.models import Task

_CLOSE_KEYWORD_RE = re.compile(r"\b(fix(e[sd])?|close[sd]?|resolve[sd]?)\s*#", re.IGNORECASE)


def _strip_close_keywords(text: str) -> str:
    """Replace GitHub auto-closing keywords with safe issue reference."""
    return _CLOSE_KEYWORD_RE.sub("issue #", text)


@dataclass(frozen=True, slots=True)
class PullRequestInfo:
    number: int
    url: str
    title: str
    body: str


class PullRequestResultKind(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


@dataclass(frozen=True, slots=True)
class PullRequestResult:
    kind: PullRequestResultKind
    info: PullRequestInfo | None
    output: str = ""


def _redact(text: str) -> str:
    return "\n".join(redact_sensitive_command_audit(tuple(text.splitlines())))


def build_pr_body(issue_number: int, summary: str = "", verification_results: str = "") -> str:
    """Build safe PR body according to SPEC (avoids auto-closing keywords)."""
    v_raw = verification_results if verification_results.strip() else "- All checks passed: PASS"
    s_raw = (
        summary.strip()
        if summary.strip()
        else f"Implementation completed for issue #{issue_number}."
    )
    v_section = _strip_close_keywords(v_raw)
    s_section = _strip_close_keywords(s_raw)
    return (
        f"Implements work for #{issue_number}.\n\n"
        f"## Summary\n\n{s_section}\n\n"
        f"## Verification\n\n{v_section}\n\n"
        f"Generated by Subscription Scheduler.\n\n"
        f"Issue is intentionally left open until review.\n"
    )


def lookup_existing_pr(
    branch_name: str,
    repo: str | None = None,
    env: dict[str, str] | None = None,
    timeout_seconds: float = 30.0,
) -> PullRequestInfo | None:
    """Lookup if an open PR already exists for this branch to ensure idempotency."""
    argv = [
        "gh",
        "pr",
        "list",
        "--head",
        branch_name,
        "--state",
        "open",
        "--json",
        "number,url,title,body",
    ]
    if repo:
        argv.extend(["--repo", repo])
    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
        if res.returncode != 0:
            return None
        data = json.loads(res.stdout)
        if not data or not isinstance(data, list):
            return None
        item = data[0]
        return PullRequestInfo(
            number=int(item["number"]),
            url=str(item["url"]),
            title=str(item["title"]),
            body=str(item.get("body", "")),
        )
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError, KeyError, ValueError):
        return None


class MergedPrCheckKind(StrEnum):
    NONE = "NONE"
    CONFIRMED = "CONFIRMED"
    AMBIGUOUS = "AMBIGUOUS"


@dataclass(frozen=True, slots=True)
class MergedPrCheckResult:
    kind: MergedPrCheckKind
    pr_number: int | None = None
    reason: str = ""


def check_merged_pr_for_issue(
    repo: str,
    issue_number: int,
    env: dict[str, str] | None = None,
    timeout_seconds: float = 30.0,
) -> MergedPrCheckResult:
    """Look for a merged PR that already implements this issue (#146: without this,
    discovery re-adds a merged-but-still-open issue as READY and duplicates work).

    Untrusted-schema handling: PR body/branch-name content from GitHub is never trusted
    blindly. Only a merged PR whose body starts with the exact Scheduler-generated
    "Implements work for #N." prefix (see build_pr_body) *and* whose branch matches the
    Scheduler's own naming convention (subsched/issue-N) is treated as CONFIRMED -- a
    strong, structural signal that the Scheduler itself created and merged this PR.
    Anything weaker (a merged PR that merely mentions the issue number, multiple
    candidates, or a gh failure) is AMBIGUOUS and must not be silently treated as
    confirmed-safe; callers fail closed on AMBIGUOUS by excluding the issue from READY
    and escalating it to NEEDS_HUMAN for manual review, matching the SPEC principle that
    the Scheduler never auto-closes or auto-completes ambiguous GitHub state.
    """
    argv = [
        "gh",
        "pr",
        "list",
        "--repo",
        repo,
        "--search",
        f"#{issue_number} in:body",
        "--state",
        "merged",
        "--json",
        "number,headRefName,body",
        "--limit",
        "10",
    ]
    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return MergedPrCheckResult(
            kind=MergedPrCheckKind.AMBIGUOUS,
            reason=(
                f"could not verify whether issue #{issue_number} already has a merged "
                "PR (gh invocation failed); review manually before treating it as READY"
            ),
        )
    if res.returncode != 0:
        return MergedPrCheckResult(
            kind=MergedPrCheckKind.AMBIGUOUS,
            reason=(
                f"could not verify whether issue #{issue_number} already has a merged "
                f"PR (gh exited {res.returncode}); review manually before treating it as READY"
            ),
        )
    try:
        data = json.loads(res.stdout)
    except json.JSONDecodeError:
        return MergedPrCheckResult(
            kind=MergedPrCheckKind.AMBIGUOUS,
            reason=(
                f"could not verify whether issue #{issue_number} already has a merged "
                "PR (unparseable gh output); review manually before treating it as READY"
            ),
        )
    if not isinstance(data, list) or not data:
        return MergedPrCheckResult(kind=MergedPrCheckKind.NONE)

    expected_prefix = f"Implements work for #{issue_number}."
    expected_branch = f"subsched/issue-{issue_number}"
    confirmed: list[int] = []
    numbers: list[str] = []
    for item in data:
        if not isinstance(item, dict):
            continue
        try:
            number = int(item["number"])
        except (KeyError, TypeError, ValueError):
            continue
        numbers.append(str(number))
        head_ref = str(item.get("headRefName", ""))
        body = str(item.get("body", ""))
        if body.startswith(expected_prefix) and head_ref == expected_branch:
            confirmed.append(number)

    if len(data) == 1 and len(confirmed) == 1:
        return MergedPrCheckResult(kind=MergedPrCheckKind.CONFIRMED, pr_number=confirmed[0])

    return MergedPrCheckResult(
        kind=MergedPrCheckKind.AMBIGUOUS,
        reason=(
            f"issue #{issue_number} is referenced by merged PR(s) "
            f"{', '.join(numbers) or '(unparseable)'} but the match could not be "
            "confirmed automatically (unexpected body/branch format); review manually "
            "before treating this issue as READY"
        ),
    )


def create_or_get_pull_request(
    task: Task,
    branch_name: str,
    base: str = "main",
    repo: str | None = None,
    verification_summary: str = "",
    env: dict[str, str] | None = None,
    timeout_seconds: float = 60.0,
) -> PullRequestResult:
    """Idempotently create or retrieve existing PR using gh CLI.

    Unlike a bare PullRequestInfo | None, PullRequestResult also carries a redacted
    `output` describing *why* creation failed (regression test for #128: this was
    previously discarded, making a resulting NEEDS_HUMAN escalation unexplainable).
    """
    existing = lookup_existing_pr(branch_name, repo=repo, env=env, timeout_seconds=timeout_seconds)
    if existing is not None:
        return PullRequestResult(kind=PullRequestResultKind.SUCCESS, info=existing)

    body = build_pr_body(
        issue_number=task.issue_number,
        summary=task.title,
        verification_results=verification_summary,
    )
    title = f"{task.title} (#{task.issue_number})"

    argv = [
        "gh",
        "pr",
        "create",
        "--head",
        branch_name,
        "--base",
        base,
        "--title",
        title,
        "--body",
        body,
    ]
    if repo:
        argv.extend(["--repo", repo])

    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
        if res.returncode != 0:
            output = _redact(f"{res.stdout}\n{res.stderr}".strip())
            return PullRequestResult(kind=PullRequestResultKind.FAILURE, info=None, output=output)
        url = res.stdout.strip()
        match = re.search(r"/pull/(\d+)", url)
        if match is None:
            return PullRequestResult(
                kind=PullRequestResultKind.FAILURE,
                info=None,
                output=_redact(f"could not parse PR number from gh output: {url}"),
            )
        pr_number = int(match.group(1))
        info = PullRequestInfo(number=pr_number, url=url, title=title, body=body)
        return PullRequestResult(kind=PullRequestResultKind.SUCCESS, info=info)
    except (OSError, subprocess.TimeoutExpired, ValueError) as error:
        return PullRequestResult(
            kind=PullRequestResultKind.FAILURE, info=None, output=_redact(str(error))
        )
