from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass
from enum import StrEnum
from pathlib import Path

from subsched.agents.process import redact_sensitive_command_audit
from subsched.models import Task

# Shared between the PR body sanitizer (_strip_close_keywords) and the commit-message
# gate (find_close_keyword_commits) so both enforce the exact same auto-close policy
# (regression test for #140: previously only PR body text was checked).
CLOSE_KEYWORD_RE = re.compile(r"\b(fix(e[sd])?|close[sd]?|resolve[sd]?)\s*#", re.IGNORECASE)


def _strip_close_keywords(text: str) -> str:
    """Replace GitHub auto-closing keywords with safe issue reference."""
    return CLOSE_KEYWORD_RE.sub("issue #", text)


@dataclass(frozen=True, slots=True)
class PullRequestInfo:
    number: int
    url: str
    title: str
    body: str


class PullRequestResultKind(StrEnum):
    SUCCESS = "SUCCESS"
    FAILURE = "FAILURE"


@dataclass(frozen=True, slots=True)
class PullRequestResult:
    kind: PullRequestResultKind
    info: PullRequestInfo | None
    output: str = ""


def _redact(text: str) -> str:
    return "\n".join(redact_sensitive_command_audit(tuple(text.splitlines())))


@dataclass(frozen=True, slots=True)
class CloseKeywordViolation:
    commit: str
    keyword_context: str


_LOG_RECORD_SEP = "\x1e"
_LOG_FIELD_SEP = "\x1f"


def find_close_keyword_commits(
    worktree_dir: Path,
    base_branch: str,
    env: dict[str, str] | None = None,
    timeout_seconds: float = 30.0,
) -> tuple[CloseKeywordViolation, ...] | None:
    """Scan commits reachable from HEAD but not from base_branch for GitHub auto-close
    keywords (Fixes/Closes/Resolves #N) anywhere in the full commit message.

    Regression coverage for #140: a worker's local commit message was never checked
    before push (only the generated PR body was sanitized), so a commit whose message
    happened to end with e.g. "Closes #130" could trigger GitHub's merge-time
    auto-close, bypassing the "issues stay open until manual review" invariant.

    Returns an empty tuple when no commit is reachable from HEAD but not base_branch,
    or when none contain a close keyword. Returns None (fail closed) if the commits
    could not be inspected at all (e.g. git failure), so the caller must not treat
    "could not check" as "clean". Never rewrites history -- read-only `git log`.
    """
    argv = [
        "git",
        "-C",
        str(worktree_dir),
        "log",
        f"{base_branch}..HEAD",
        f"--format=%H{_LOG_FIELD_SEP}%B{_LOG_RECORD_SEP}",
    ]
    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
    except (OSError, subprocess.TimeoutExpired):
        return None
    if res.returncode != 0:
        return None

    violations: list[CloseKeywordViolation] = []
    for record in res.stdout.split(_LOG_RECORD_SEP):
        record = record.strip("\n")
        if not record:
            continue
        commit_sha, _, message = record.partition(_LOG_FIELD_SEP)
        if CLOSE_KEYWORD_RE.search(message):
            violations.append(
                CloseKeywordViolation(
                    commit=commit_sha[:12], keyword_context=_redact(message.strip())
                )
            )
    return tuple(violations)


def build_pr_body(issue_number: int, summary: str = "", verification_results: str = "") -> str:
    """Build safe PR body according to SPEC (avoids auto-closing keywords)."""
    v_raw = verification_results if verification_results.strip() else "- All checks passed: PASS"
    s_raw = (
        summary.strip()
        if summary.strip()
        else f"Implementation completed for issue #{issue_number}."
    )
    v_section = _strip_close_keywords(v_raw)
    s_section = _strip_close_keywords(s_raw)
    return (
        f"Implements work for #{issue_number}.\n\n"
        f"## Summary\n\n{s_section}\n\n"
        f"## Verification\n\n{v_section}\n\n"
        f"Generated by Subscription Scheduler.\n\n"
        f"Issue is intentionally left open until review.\n"
    )


def lookup_existing_pr(
    branch_name: str,
    repo: str | None = None,
    env: dict[str, str] | None = None,
    timeout_seconds: float = 30.0,
) -> PullRequestInfo | None:
    """Lookup if an open PR already exists for this branch to ensure idempotency."""
    argv = [
        "gh",
        "pr",
        "list",
        "--head",
        branch_name,
        "--state",
        "open",
        "--json",
        "number,url,title,body",
    ]
    if repo:
        argv.extend(["--repo", repo])
    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
        if res.returncode != 0:
            return None
        data = json.loads(res.stdout)
        if not data or not isinstance(data, list):
            return None
        item = data[0]
        return PullRequestInfo(
            number=int(item["number"]),
            url=str(item["url"]),
            title=str(item["title"]),
            body=str(item.get("body", "")),
        )
    except (OSError, subprocess.TimeoutExpired, json.JSONDecodeError, KeyError, ValueError):
        return None


def create_or_get_pull_request(
    task: Task,
    branch_name: str,
    base: str = "main",
    repo: str | None = None,
    verification_summary: str = "",
    env: dict[str, str] | None = None,
    timeout_seconds: float = 60.0,
) -> PullRequestResult:
    """Idempotently create or retrieve existing PR using gh CLI.

    Unlike a bare PullRequestInfo | None, PullRequestResult also carries a redacted
    `output` describing *why* creation failed (regression test for #128: this was
    previously discarded, making a resulting NEEDS_HUMAN escalation unexplainable).
    """
    existing = lookup_existing_pr(branch_name, repo=repo, env=env, timeout_seconds=timeout_seconds)
    if existing is not None:
        return PullRequestResult(kind=PullRequestResultKind.SUCCESS, info=existing)

    body = build_pr_body(
        issue_number=task.issue_number,
        summary=task.title,
        verification_results=verification_summary,
    )
    title = f"{task.title} (#{task.issue_number})"

    argv = [
        "gh",
        "pr",
        "create",
        "--head",
        branch_name,
        "--base",
        base,
        "--title",
        title,
        "--body",
        body,
    ]
    if repo:
        argv.extend(["--repo", repo])

    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
        if res.returncode != 0:
            output = _redact(f"{res.stdout}\n{res.stderr}".strip())
            return PullRequestResult(kind=PullRequestResultKind.FAILURE, info=None, output=output)
        url = res.stdout.strip()
        match = re.search(r"/pull/(\d+)", url)
        if match is None:
            return PullRequestResult(
                kind=PullRequestResultKind.FAILURE,
                info=None,
                output=_redact(f"could not parse PR number from gh output: {url}"),
            )
        pr_number = int(match.group(1))
        info = PullRequestInfo(number=pr_number, url=url, title=title, body=body)
        return PullRequestResult(kind=PullRequestResultKind.SUCCESS, info=info)
    except (OSError, subprocess.TimeoutExpired, ValueError) as error:
        return PullRequestResult(
            kind=PullRequestResultKind.FAILURE, info=None, output=_redact(str(error))
        )
