from __future__ import annotations

import json
import re
import subprocess
from dataclasses import dataclass

from subsched.models import Task


@dataclass(frozen=True, slots=True)
class PullRequestInfo:
    number: int
    url: str
    title: str
    body: str


def build_pr_body(issue_number: int, summary: str = "", verification_results: str = "") -> str:
    """Build safe PR body according to SPEC (avoids 'Fixes' or 'Closes')."""
    v_section = (
        verification_results if verification_results.strip() else "- All checks passed: PASS"
    )
    s_section = (
        summary.strip()
        if summary.strip()
        else f"Implementation completed for issue #{issue_number}."
    )
    return (
        f"Implements work for #{issue_number}.\n\n"
        f"## Summary\n\n{s_section}\n\n"
        f"## Verification\n\n{v_section}\n\n"
        f"Generated by Subscription Scheduler.\n\n"
        f"Issue is intentionally left open until review.\n"
    )


def lookup_existing_pr(
    branch_name: str,
    repo: str | None = None,
    env: dict[str, str] | None = None,
    timeout_seconds: float = 30.0,
) -> PullRequestInfo | None:
    """Lookup if an open PR already exists for this branch to ensure idempotency."""
    argv = [
        "gh",
        "pr",
        "list",
        "--head",
        branch_name,
        "--state",
        "open",
        "--json",
        "number,url,title,body",
    ]
    if repo:
        argv.extend(["--repo", repo])
    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
        if res.returncode != 0:
            return None
        data = json.loads(res.stdout)
        if not data or not isinstance(data, list):
            return None
        item = data[0]
        return PullRequestInfo(
            number=int(item["number"]),
            url=str(item["url"]),
            title=str(item["title"]),
            body=str(item.get("body", "")),
        )
    except Exception:
        return None


def create_or_get_pull_request(
    task: Task,
    branch_name: str,
    base: str = "main",
    repo: str | None = None,
    verification_summary: str = "",
    env: dict[str, str] | None = None,
    timeout_seconds: float = 60.0,
) -> PullRequestInfo | None:
    """Idempotently create or retrieve existing PR using gh CLI."""
    existing = lookup_existing_pr(branch_name, repo=repo, env=env, timeout_seconds=timeout_seconds)
    if existing is not None:
        return existing

    body = build_pr_body(
        issue_number=task.issue_number,
        summary=task.title,
        verification_results=verification_summary,
    )
    title = f"{task.title} (#{task.issue_number})"

    argv = [
        "gh",
        "pr",
        "create",
        "--head",
        branch_name,
        "--base",
        base,
        "--title",
        title,
        "--body",
        body,
    ]
    if repo:
        argv.extend(["--repo", repo])

    try:
        res = subprocess.run(
            argv,
            stdin=subprocess.DEVNULL,
            capture_output=True,
            text=True,
            errors="replace",
            timeout=timeout_seconds,
            env=env,
            check=False,
        )
        if res.returncode != 0:
            return None
        url = res.stdout.strip()
        match = re.search(r"/pull/(\d+)", url)
        pr_number = int(match.group(1)) if match else 0
        return PullRequestInfo(number=pr_number, url=url, title=title, body=body)
    except Exception:
        return None
